import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

# 1. Load the data generated by your C script
try:
    df = pd.read_csv('simulation_results.csv')
except FileNotFoundError:
    print("Error: simulation_results.csv not found. Run the C program first!")
    exit()

# --- CUTOFF LOGIC ---
# We want to find the point where Real_G stays near 0 for ~2 seconds.
# 1. Calculate the sampling rate (dt)
dt = df['Time'].iloc[1] - df['Time'].iloc[0]
samples_in_2s = int(2.0 / dt)

# 2. Find where acceleration is "near zero" (e.g., within 0.02 G)
is_zero = df['Real_G'].abs() < 0.02

# 3. Look for a window of 2 seconds where is_zero is True
# We only start looking after the rocket has launched (acceleration > 0.5G)
launched_idx = (df['Real_G'] > 0.5).idxmax()
cutoff_idx = len(df)

for i in range(launched_idx, len(df) - samples_in_2s):
    if is_zero.iloc[i : i + samples_in_2s].all():
        # We found the landing/stop point. 
        # Add a small buffer (1 second) so the graph doesn't end abruptly.
        cutoff_idx = i + int(1.0 / dt) 
        break

# Trim the dataframe
df = df.iloc[:cutoff_idx]
# --------------------

# 2. Set the visual style
plt.style.use('dark_background')
fig, (ax1, ax2, ax3, ax4) = plt.subplots(4, 1, figsize=(12, 24))

# GRAPH 1: Altitude Sensor Fusion
ax1.plot(df['Time'], df['Real_Alt'], color='#00FF00', label='Real Altitude', linewidth=3, alpha=0.8)
ax1.scatter(df['Time'], df['Baro_Alt'], color='#FF4500', s=12, alpha=0.4, label='Noisy Baro')
ax1.plot(df['Time'], df['kf_altitude'], color='#FFFFFF', label='KF Estimate', linewidth=2, linestyle='--')
ax1.set_title('Altitude Sensor Fusion (Kalman Filter)', fontsize=14, pad=15)
ax1.set_ylabel('Meters')
ax1.legend(loc='upper left')
ax1.grid(True, alpha=0.2)

# GRAPH 2: Velocity Estimation
ax2.plot(df['Time'], df['Real_Vel'], color='#FFA500', label='Real Velocity', linewidth=3, alpha=0.8)
ax2.plot(df['Time'], df['kf_velocity'], color='#FFFFFF', label='KF Velocity Estimate', linewidth=2, linestyle='--')
ax2.set_title('Velocity Estimation Accuracy', fontsize=14, pad=15)
ax2.set_ylabel('m/s')
ax2.legend(loc='upper left')
ax2.grid(True, alpha=0.2)

# GRAPH 3: Acceleration Comparison (Input Signals)
ax3.plot(df['Time'], df['Real_G'], color='#00BFFF', label='Real Accel (G)', linewidth=3, alpha=0.8)
ax3.scatter(df['Time'], df['Sens_G'], color='#DA70D6', s=12, alpha=0.4, label='Raw Sensor Accel (G)')
ax3.set_title('Acceleration Comparison (Input Signal)', fontsize=14, pad=15)
ax3.set_ylabel('G-Force')
ax3.legend(loc='upper left')
ax3.grid(True, alpha=0.2)

# GRAPH 4: Ground Truth Mission Profile
ax4.plot(df['Time'], df['Real_Alt'] - df['Real_Alt'].iloc[0], color='#00FF00', label='Alt Change (m)')
ax4.plot(df['Time'], df['Real_Vel'], color='#FFA500', label='Velocity (m/s)')
ax4.plot(df['Time'], df['Real_G'], color='#00BFFF', label='Acceleration (G)')
ax4.set_title('Ground Truth Mission Profile (Truncated)', fontsize=14, pad=15)
ax4.set_xlabel('Time (seconds)')
ax4.legend(loc='upper left')
ax4.grid(True, alpha=0.2)

plt.tight_layout()
plt.show()